### ISSUE TITLE
#9 Has bug

### ISSUE THREAD

**Issue by comjun04** [seoaapp/SeoaBot#10]
#9 has bug

**Comment by pmh-only** [comment]
System Log is here
![image](https://user-images.githubusercontent.com/39158228/62032768-6fc18b80-b225-11e9-90f7-8facff9a5335.png)

**Comment by pmh-only** [comment]
randomHexColor() module function returns **String**
so, didn't work

**Comment by pmh-only** [comment]
We solve this problem, thanks for issue
