### ISSUE TITLE
Help Bug

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaBot#11]
https://github.com/seoaapp/SeoaBot/blob/master/commands/help.js#L20

**Comment by comjun04** [comment]
Why is it a bug?

**Comment by ttakkku** [comment]
저거 파일(*.js)에 helps 읽어서 출력 하는 건데 안된다는 점

**Comment by Helloyunho** [comment]
Fixed by #12.

**Comment by ttakkku** [comment]
@Helloyunho  Thank you :D
