### ISSUE TITLE
CodeQuiz Database

### ISSUE THREAD

**Issue by comjun04** [seoaapp/SeoaBot#15]
Which database will this service use?

**Comment by Helloyunho** [comment]
I found this: https://github.com/rethinkdb/rethinkdb

It's JSON-like DB, and it already hit 22440 stars so I think this can be our main DB.

**Comment by comjun04** [comment]
Working on RethinkDB.
When completed, this issue will closed.

**Comment by pmh-only** [comment]
Issue Closed
