### ISSUE TITLE
QuizRequest: 아희는 한글로 작성한다.

### ISSUE THREAD

**Issue by comjun04** [seoaapp/SeoaBot#19]
# Quiz Request
## Quiz Language (Programming Language)
* 아희

## Question
아희는 한글로 작성한다.

## Answer (Choose Only One)
- [x] O
- [ ] X

아희는 한글로 된 언어이기 때문에 **당연히** 한글로 작성합니다.

**Comment by gnlow** [comment]
아희는 **한국어**가 아니라 **한글**로 작성하는 것이 아닌가요?

**Comment by comjun04** [comment]
어 그렇네요 수정하겟습니다.

**Comment by pmh-only** [comment]
반영했습니다
