### ISSUE TITLE
QuizRequest: HTTPS는 HTTP보다 보안이 강하다.

### ISSUE THREAD

**Issue by kellsthepenguin** [seoaapp/SeoaBot#28]
## 문제의 언어 Quiz Language (Programming Language)
Plain(HTTP)

## 문제 Question
QuizRequest: HTTPS는 HTTP보다 보안이 강하다.

## 답 Answer
- [x] O
- [ ] X

## 풀이 Answer Explanation
HTTPS는 SSL이 사이에 껴있기 때문에 당연히 HTTP보다 보안이 강합니다.

**Comment by pmh-only** [comment]
SSL이 사이에 껴있기 때문에 ->  SSL위에서 작동하기 때문에

**Comment by pmh-only** [comment]
http는 언어가 아니므로 genaral로 적용되었습니다
