### ISSUE TITLE
퀴즈 리더보드 작동 안함

### ISSUE THREAD

**Issue by R2turnTrue** [seoaapp/SeoaBot#29]
# Bug Report
### What is the bug?
`>리더` 명령어가 작동하지 않습니다.

### Steps to reproduce
1. Enter the steps here
2. to reproduce the bug.

### Additional Information
(optional)

**Comment by ghost** [comment]
지금 그 부분 수정 중에 있습니다.

**Comment by ttakkku** [comment]
수정 했습니다
