### ISSUE TITLE
서버에 안좋은 버그가 하나 있습니다

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/SeoaBot#34]
어이쿠 FFmpeg를 어떻게 까는지 모르겠네?
까는법 알려주시면 감사하겠습니다

**Comment by pmh-only** [comment]
참고로 서버는 우분투 19.04 x64

**Comment by ttakkku** [comment]
https://yujuwon.tistory.com/entry/우분투에서-ffmpeg-설치-방법

**Comment by ttakkku** [comment]
@PMHStudio  이거 되나여?

**Comment by pmh-only** [comment]
네네 해결되었습니다
