### ISSUE TITLE
예상치 못한 버그 ㄴㅇㄱ

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/SeoaBot#36]
https://github.com/seoaapp/SeoaBot/blob/722f39ceb4633eb02bb28053410e961ea479c749/seoa.js#L136 에 보시면

``!msg.guild`` 에서 어떻게 ``locale: settings.servers[msg.guild.id].lang``을 하죠..?

**Comment by ttakkku** [comment]
그럼 무조건 영어만 나오게 하면 되죠 ㄴㅇㄱ

**Comment by pmh-only** [comment]
그건 쫌;;

ex)
한국어 설정한 서버에서 >help를 침 -> DM으로 한글 help가 옴 -> 한번 쳐보고 싶어서 DM에서 쳤더니 갑자기 영어가? ㄴㅇㄱ

**Comment by ttakkku** [comment]
네 그러는 게 좋을 듯 ㄴㅇㄱ

**Comment by pmh-only** [comment]
ㄴㅇㄱ!?

**Comment by pmh-only** [comment]
그냥 영어, 한국어, pt어로 DM에서 커멘드 실행 안된다고 다 순서대로 다 적죠

**Comment by comjun04** [comment]
저 문장만 번역 안하고 다 적..?

**Comment by pmh-only** [comment]
아니면 DM에서도 사용할 수 있게 할까요?

**Comment by ghost** [comment]
그냥 언어 설정을 개인별로 설정하게 하는것이 좋지 않을까요 그게 제일 오류 날 일 없고 좋을 거 같은데

**Comment by ttakkku** [comment]
저건 모든 언어로 쓰는 걸로 합시다

**Comment by pmh-only** [comment]
음... 네
