### ISSUE TITLE
quizs.json 오탈자 및 어체 통일의 대한건

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/SeoaBot#39]
## 오탈자 목록
1. - [x] awnser -> answer
2. - [x] genaral -> general

## quizs.json의 어체들
1. 경어체 (~합니다)
2. 평어체 (~하다)

-----------------

오탈자는 바로 고쳐주시고, 어체는 의견 받습니다

**Comment by comjun04** [comment]
완료 표시용 체크박스 넣었습니다

**Comment by pmh-only** [comment]
네넷

**Comment by ghost** [comment]
경어체보다는 많은 분들이 보실텐데 평어체가 낫지 않을까요?

**Comment by pmh-only** [comment]
예시입니다
1. 경어: C언어에서 문자열(String)을 선언할 때, 문자(char.)의 배열(Array)을 사용합니다.
2. 평어: html에서 줄바꿈을 하려고 하면 \<br>을 입력해야 한다.

**Comment by comjun04** [comment]
한국어의 경우
*불특정 다수가 볼 수 있는 문장 등은 경어체로 한다*는 등의 지침이 있었던 걸로 압니다

**Comment by pmh-only** [comment]
경어체가 저도 낫다고 봅니다

**Comment by ttakkku** [comment]
저도 경어체가 낮다고 봅니다

**Comment by pmh-only** [comment]
그럼 경어체로 통일 하는것으로 결정되었습니다 [땅땅땅]

**Comment by ttakkku** [comment]
이제부터 그렇게 된 건가요?

**Comment by pmh-only** [comment]
기존에 있던 퀴즈들도 경어체로 통일해주시면 됩니다
