### ISSUE TITLE
html에서 css파일 연동 방법

### ISSUE THREAD

**Issue by ghost** [seoaapp/SeoaBot#40]
## 문제의 언어 Quiz Language (Programming Language)
HTML

## 문제 Question (OX로 문제를 풀수있어야 합니다 Yes/No quiz)
HTML에서 css 파일과 연동하기 위해서 아래의 태그를 사용해야 합니다.
<link rel="stylesheet" href="css_link.css">

## 답 Answer
O

## 풀이 Answer Explanation
https://www.w3schools.com/tags/tag_link.asp
위의 페이지로 들어가시면 <link>태그로 css를 연동 할 수 있음을 알 수 있습니다.

**Comment by pmh-only** [comment]
더 상세한 풀이를 적어 주십시오

**Comment by ghost** [comment]
이렇게 적으면 되나요?

**Comment by ttakkku** [comment]
....

**Comment by ghost** [comment]
html도 일종의 코딩 언어 아닌가요?

**Comment by Helloyunho** [comment]
...

**Comment by comjun04** [comment]
`html`은 **마크업 언어**라고는 알고 있는데
코딩 언어인가..?

**Comment by noamboy2006** [comment]
코딩언어는 아니라는것이 정설 아닌가요?

**Comment by pmh-only** [comment]
html은 프로그래밍 언어 취급을 받지는 못하고 있지만
CodeQuiz에서는 퀴즈가 그렇게 많지는 않기때문에 환영입니다

**Comment by pmh-only** [comment]
근데 풀이가 아직도 부족한거 같네요

**Comment by pmh-only** [comment]
풀이 개선후 다시 열어주세요

**Comment by ghost** [comment]
더 자세한 풀이 방법이 생각나지 않기 때문에
이 문제 삭제해 주시기 바랍니다.
