### ISSUE TITLE
SeoaBot Roadmap

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaBot#43]
> `node seoa.js` or `node shard.js` 실행 할떄 `./ServerData/`,  `./UserData/`  없으면 생성하고 
그리고 `./ServerData/servers.json`, `./ServerData/owners.json`, `./UserData/users.json` 없으면 
생성한다.

========
나중에 추가 할 거 생기면 편집해야징~

**Comment by pmh-only** [comment]
네 이미 있었죠

**Comment by ttakkku** [comment]
@PMHStudio  
![image](https://user-images.githubusercontent.com/42809517/62817003-7d064080-bb6a-11e9-80dd-dc041d7046c6.png)

**Comment by ttakkku** [comment]
수리 해야 하는 데
