### ISSUE TITLE
문제 추가! Quiz Request: const, let와 var은 모두 똑같은 기능을 가진 "선언문"입니다.

### ISSUE THREAD

**Issue by zero734kr** [seoaapp/SeoaBot#45]
이 템플릿은 **한국어**와 영어로 쓰여 있습니다.
This template is both written Korean and **English**.

(꼭, **이슈 하나당 하나의 문제**만 적어주세요! Please write **only one question per issue!**)

## 문제의 언어 Quiz Language (Programming Language)
e.g. Python 3

## 문제 Question (OX로 문제를 풀수있어야 합니다 Yes/No quiz)
여기에 문제를 입력해 주세요. (~에서는 ~해서 ~한다.) Enter question here

## 답 Answer
- [x] O
- [ ] X

## 풀이 Answer Explanation
( 자세하게 해줘요! Write it detailed! )

## 사진 (선택) Image (Optional)
[사진 설명 Image Description](https://해당-사진의-링크/enter-your-image-link-here)

**Comment by pmh-only** [comment]
어 음 이렇게 해달라는 말이 아니였..

**Comment by pmh-only** [comment]
#46 으로 옴겼습니다
