### ISSUE TITLE
문제 추가! Quiz Request: const, let와 var은 모두 똑같은 기능을 가진 "선언문"입니다.

### ISSUE THREAD

**Issue by zero734kr** [seoaapp/SeoaBot#46]
이 템플릿은 **한국어**와 영어로 쓰여 있습니다.
This template is both written Korean and **English**.

(꼭, **이슈 하나당 하나의 문제**만 적어주세요! Please write **only one question per issue!**)

## 문제의 언어 Quiz Language (Programming Language)
e.g. JavaScript

## 문제 Question (OX로 문제를 풀수있어야 합니다 Yes/No quiz)
const, let와 var은 모두 똑같은 기능을 가진 "선언문"이다.

## 답 Answer
- [ ] O
- [x] X

## 풀이 Answer Explanation
모두 다른 기능입니다. const는 똑같은 이름을 가진 선언문이 있다면 오류를 뜨게 해 겹쳐서는 안 될 모듈을 불러오는데 적합하며, let는 해당 scope(e.g: if(...) { let y = null }, 여기서 scope는 {}) 안에서만 효력을 가지며 var은 선언이 scope 밖으로 hoist(위에 고정)되어 여러개의 var과 조건문의 결합으로 정보를 조작할수 있는 선언문입니다.

## 사진 (선택) Image (Optional)
[사진 설명 Image Description](https://해당-사진의-링크/enter-your-image-link-here)

**Comment by pmh-only** [comment]
네넷 빨리 추가해 드릴깨요

**Comment by comjun04** [comment]
문제 반영 확인하였습니다.
