### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaBot#48]
# Bug Report
### What is the bug?
explain here. Please give the information as many as you can.

### Steps to reproduce
1. Enter the steps here
2. to reproduce the bug.

### Additional Information
(optional)

**Comment by ttakkku** [comment]
어 왜 안되지 흠

**Comment by ttakkku** [comment]
ㅇㅎ 되네

**Comment by PMHStudio** [comment]
뭐지 바보인강
