### ISSUE TITLE
Quiz Request : 퀘엨

### ISSUE THREAD

**Issue by ghost** [seoaapp/SeoaBot#51]
이 템플릿은 **한국어**와 영어로 쓰여 있습니다.
This template is both written Korean and **English**.

(꼭, **이슈 하나당 하나의 문제**만 적어주세요! Please write **only one question per issue!**)

## 문제의 언어 Quiz Language (Programming Language)
e.g. Python 3
맞아요 python 3

## 문제 Question (OX로 문제를 풀수있어야 합니다 Yes/No quiz)
여기에 문제를 입력해 주세요. (~에서는 ~해서 ~한다.) Enter question here

Python 의 if문이다. 실행해서 random 값이 3이면 Yee 가 출력되는가?

```
me = ["Yay", "Noo", "IDK"]
random = random.randint(1, 3)
mee = me[random]

if mee is not None:
    print(mee)
else:
    print("Yee")
```

## 답 Answer
- [v] O
- [ ] X

## 풀이 Answer Explanation
( 자세하게 해줘요! Write it detailed! )
파이썬의 리스트 개념은 1부터 시작하는 것이 아닌, 0 부터 시작하는데, 코드에서는 3개가 주어졌다. 즉, Yay = 0 Noo = 1 IDK = 2 임에 따라 3은 지정되지 않았다. 따라서 3이 나왔다면 me의 3번째를 얻어오는 mee는 None 이 될 수 밖에 없고, Yee 를 출력하게 된다.
## 사진 (선택) Image (Optional)
[사진 설명 Image Description](https://해당-사진의-링크/enter-your-image-link-here)

**Comment by pmh-only** [comment]
확인되었습니다, 빠른 시일내에 추가될 예정입니다
