### ISSUE TITLE
천마님의 건의

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaBot#58]
1. 명령어 쓸때마다 봇정보 나오는대 수정

컨셉의 기능을
총 10가지정도
짜오시고
저거 포함 기능을
Basic포함
23개이상
짜와주세요

여기서
Basic이란
핑
유저정보
서버정보
등의

**Comment by pmh-only** [comment]
가짜 토큰이 보이게 하죠

**Comment by ttakkku** [comment]
이 건의는 서버에 아이디어 채널로 옴겨갔습니다
