### ISSUE TITLE
Error Invite Command

### ISSUE THREAD

**Issue by ttakkku** [seoaapp/SeoaBot#6]
![image](https://user-images.githubusercontent.com/42809517/59446954-747cdc80-8e3d-11e9-9e4e-73c67e28d758.png)

https://github.com/ttakkku/SeoaBot/blob/master/commands/Invite.js#L2

**Comment by pmh-only** [comment]
Do you add that command to dialogflow?

**Comment by ttakkku** [comment]
No @PMHStudio

**Comment by pmh-only** [comment]
Fixed already :smiley:

**Comment by ttakkku** [comment]
What???

**Comment by pmh-only** [comment]
It's not a code problem

**Comment by pmh-only** [comment]
I just trained dialogflow

**Comment by ttakkku** [comment]
Opus..

**Comment by pmh-only** [comment]
Not your fault

**Comment by pmh-only** [comment]
Let's close this

**Comment by ttakkku** [comment]
Okay Thx!
