### ISSUE TITLE
How to run in linux os?

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/SeoaBot#62]
Hello, I'm the hosting manager of this project
I wanna host this. But, my host server is Ubuntu 18.04
There isn't any manual?

**Comment by Helloyunho** [comment]
Do it as usually.

1. run `npm install`(Or something)

2. run `npm run Client` after you assign `TOKEN` env.

**Comment by pmh-only** [comment]
Is that configure sql too?

**Comment by Helloyunho** [comment]
I'm not sure, but I remember it does.

**Comment by pmh-only** [comment]
Um.. Okay I'll try it

**Comment by isulbi** [comment]
데이터베이스 설정은 직접 mysql 또는 mariadb에서 덤프된 파일(seoa.sql)을 실행하셔야 합니다.

**Comment by pmh-only** [comment]
so how to do that

**Comment by ttakkku** [comment]
mysql> source seoa.sql

@PMHStudio

**Comment by pmh-only** [comment]
Let's make Manual about that

**Comment by pmh-only** [comment]
![image](https://user-images.githubusercontent.com/39158228/64916942-d2b2b600-d7c4-11e9-8569-fc8b9bc4fc98.png)
Wait, where is userdata table?

**Comment by isulbi** [comment]
구버전의 mysql branch의 경우 덤프 파일의 구문에 약간 오류가 발생하여 userdata 테이블이 사라지는 현상이 있었으나, 최신 버전의 mysql branch에는 이 문제가 해결되어 있습니다.
**다시 다운로드 받으시길 바랍니다**

**Comment by pmh-only** [comment]
Fu...

**Comment by pmh-only** [comment]
![image](https://user-images.githubusercontent.com/39158228/64917131-24a90b00-d7c8-11e9-9f5d-5176ba07c056.png)
Ah now working...

**Comment by pmh-only** [comment]
It solved!
But, We need to make a manual
