### ISSUE TITLE
master branch 관련

### ISSUE THREAD

**Issue by isulbi** [seoaapp/SeoaBot#67]
## master branch 방치?
데이터베이스를 `mysql`로 마이그레이션 하면서 `master branch`는 방치가 되었습니다.
## 왜 마이그레이션을 했는가?
`dialogflow`를 데이터베이스로 하는 것은 구조상 `mysql` 보다 비효율 적이며, 
애초부터 데이터베이스 용으로 제작된 것이 아니라 챗봇을 만들기 위하여 제작된 것이므로
사용을 하지 않는게 맞다고 생각하게 되었기 때문입니다.
## master branch에 있는 구조가 더 익숙하다. 다시 되돌려 달라.
최적화에 영향이 가지 않는 이상 `UnderC/SeoaBot`에서 issue 또는 PR를 넣어주시면
다시 구조를 롤백하도록 하겠습니다.
더 좋은 데이터베이스 엔진이 있다면 issue 또는 PR를 넣어주시면 적극 반영하도록 하겠습니다.
## 결론
`master branch`에 있는 구조를 원하면 issue 또는 PR를 넣으면 최대한 반영을 하도록 노력.
`dialogflow`는 데이터베이스 용으로 제작된게 아니라 `mysql` 보다 성능 및 효율이 떨어짐.
`master branch`를 개발하지 않고, `mysql branch`를 개발하기.

> 추가로 현재 구동되고 있는 서아봇은 `mysql`를 사용합니다.

**Comment by ttakkku** [comment]
@UnderC  그럼 json로 거의 개발 및 지원하는 게 끝났으니 master를 mysql 로 옴기고 json 이라고 저장용으로 하겠습니다

**Comment by ttakkku** [comment]
![image](https://user-images.githubusercontent.com/42809517/65867601-af395f00-e3b1-11e9-8985-e3f3dec8de74.png)


수정 완료
