### ISSUE TITLE
About Moving Repo

### ISSUE THREAD

**Issue by pmh-only** [seoaapp/SeoaBot#7]
@ttakkku 
이 레포지트리 [SeoaApp org.](https://github.com/SeoaApp)로 옴겨야 하지 않을까요?

**Comment by ttakkku** [comment]
나중에 옴길 생각입니다

**Comment by ttakkku** [comment]
@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다@PMHStudio  옴겼습니다

**Comment by comjun04** [comment]
~~Why are you making like an `ascii art`?~~
